# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- pwsh: |
    $env:PSModulePath = "/usr/share/az_2.8.0:" + $env:PSModulePath;
    $clientId = $env:AZURE_CLIENT_ID
    $secret = ConvertTo-SecureString -String $env:AZURE_CLIENT_SECRET -AsPlainText -Force
    $tenantId = $env:AZURE_TENANT_ID
    $cred = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $clientId, $secret
    Connect-AzAccount -Credential $cred -Tenant $tenantId -ServicePrincipal
  env:
    AZURE_CLIENT_ID: $(ClientId)
    AZURE_CLIENT_SECRET: $(ClientSecret)
    AZURE_TENANT_ID: $(TenantId)
  displayName: 'Login to Azure'
- pwsh: . .\Deploy-AzTemplate.ps1 . -Location "westus2"
  displayName: 'Deploy to Azure'
