name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to Azure
      shell: pwsh
      run: |
        $clientId = "${{ secrets.AZURE_CLIENT_ID }}"
        $secret = ConvertTo-SecureString -String "${{ secrets.AZURE_CLIENT_SECRET }}" -AsPlainText -Force
        $tenantId = "${{ secrets.AZURE_TENANT_ID }}"
        $cred = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $clientId, $secret
        Install-Module -Name "Az" -Scope CurrentUser -Force 
        Connect-AzAccount -Credential $cred -Tenant $tenantId -ServicePrincipal
